include(CMakePackageConfigHelpers)

# Install current project
# This macro will install the current project as a CMake package, assume that the `targets_export_filename` is `${PROJECT_NAME}Targets.cmake`, including:
# - executables to `${CMAKE_INSTALL_BINDIR}` directory
# - libraries to `${CMAKE_INSTALL_LIBDIR}` directory
# - header files (the whole `include/${PROJECT_NAME}` directory) to `${CMAKE_INSTALL_INCLUDEDIR}` directory
# - ${PROJECT_NAME}Config.cmake (generated from `input_targets_config_file`) to `${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}` directory
# - ${PROJECT_NAME}ConfigVersion.cmake (generated by this macro) to `${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}` directory
# - ${PROJECT_NAME}Targets.cmake (generated by cmake) to `${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}` directory
# - ${PROJECT_NAME}Targets-${build_type}.cmake (generated by cmake) to `${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}` directory
#
# [ARGV0] `targets`: the targets to install
# [ARGV1] `input_targets_config_file`: the path to the targets config file
# [ARGV2] `version`: the version of the project
# [ARGV3] `version_compatibility`: the version compatibility for the generated ConfigVersion
# [ARGV4] `targets_export_filename`: the filename for the targets export
macro(InstallProject targets input_targets_config_file version version_compatibility targets_export_filename)
    include(GNUInstallDirs)

    # install version config file
    write_basic_config_version_file(
        "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}ConfigVersion.cmake"
        VERSION ${version}
        COMPATIBILITY ${version_compatibility}
    )
    install(
        FILES "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}ConfigVersion.cmake"
        DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"
    )

    # install headers
    install(
        DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/include/${PROJECT_NAME}"
        DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
    )

    # install targets and package config file
    install(
        TARGETS ${${targets}}
        EXPORT ${PROJECT_NAME}Targets
        RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
        LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
        ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    )
    configure_package_config_file(
        "${input_targets_config_file}" "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
        INSTALL_DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"
    )
    install(
        FILES "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
        DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"
    )
    install(EXPORT ${PROJECT_NAME}Targets
        FILE "${targets_export_filename}"
        NAMESPACE ${PROJECT_NAME}::
        DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"
    )
endmacro()
